import styled from '@emotion/styled';
import { Typography } from '@mui/material';
import { useTheme } from '@mui/material/styles';
import useMediaQuery from '@mui/material/useMediaQuery';
import React from 'react';

import { Subheading } from '../Common.styles';

//TODO:  Update styling once Figma designs are finished.  The live RA, which is where the styling is from,
// doesn't match up with the design system.
export default function Company() {
  const theme = useTheme();

  const CompanyLink = styled.a`
    color: #aaabd1;
    font-size: 11px;
    text-decoration: underline;
    font-style: italic;
    margin: 6px 0;
  `;
  const CompanyDescription = styled.p`
    font-size: 12px;
    line-height: 1.67;
    letter-spacing: 0.09px;
  `;

  const CompanyCard = styled.div`
    ${useMediaQuery(theme.breakpoints.down('lg'))
      ? 'padding-top: 0;'
      : 'padding-top: 12px;'}
    display: grid;
    grid-template-columns: 100%;
    overflow: hidden;
    align-content: baseline;
  `;

  return (
    <CompanyCard>
      <Typography
        variant="h1"
        sx={{
          padding: 0,
          margin: 0,
          marginBottom: '15px',
          fontWeight: 300,
          fontSize: '16px',
          color: theme.palette.grey[800],
          fontFamily: 'Merriweather, sans-serif',
        }}
      >
        Company Summary
      </Typography>
      <Subheading>International Business Machines Corp. (IBM)</Subheading>
      <CompanyLink href="javascript:;">www.ibm.com/</CompanyLink>
      <CompanyDescription>
        International Business Machines Corporation (IBM) is an American multinational
        technology corporation headquartered in Armonk, New York, with operations in over
        171 countries. IBM produces and sells computer hardware, middleware and software,
        and provides hosting and consulting services in areas ranging from mainframe
        computers to nanotechnology. IBM is also a major research organization, holding
        the record for most annual U.S. patents generated by a business (as of 2020) for
        28 consecutive years.
      </CompanyDescription>
    </CompanyCard>
  );
}
