name: Publish @ui-kit-2022/theme to npmjs
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Node 
        working-directory: packages/ui-kit-theme
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
          scope: '@ui-kit-2022'
          cache: npm

      - name: Install
        run: yarn

      - name: Build
        run: yarn build-lib

      - name: Publish
        working-directory: packages/ui-kit-theme
        run: | 
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          echo "@ui-kit-2022:registry=https://registry.npmjs.org" >> ~/.npmrc
          echo 'always-auth=true' >> ~/.npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
